[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
sfui =  { path = "../../" }
console_log = { version = "0.2", features = ["color"] }
log = "0.4"
console_error_panic_hook = "0.1.7"
async-trait = "0.1.58"
